---
title: "Main Text Figures for 'Estimating the effects of a California gun control program with Multitask Gaussian Processes'"
author: "Eli Ben-Michael, David Arbour, Avi Feller, Alexander Franks, and Steven Raphael"
date: "July 2022"

output: 
  html_document: default
  self_contained: no
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "pdf")
library(haven)
library(tidyverse)
library(cmdstanr)
library(posterior)
library(lmtest)
library(broom)
library(readxl)
library(ggrepel)
library(patchwork)
library(tidybayes)
library(augsynth)
library(ggridges)

options(digits=3)
options(dev = "pdf")
# opts_chunk$set(dev = "pdf")

knitr::opts_chunk$set(dev = "pdf")
knitr::opts_chunk$set(fig.path = "../figs/paper/")
```

```{r load_data, include=F}

start_year <- 1997
end_year <- 2016

t_int <- 2007

guns <- read_dta("../data/ucrpanel2.dta")

crimes <- read_dta("../data/ucrthrough2018.dta") %>%
    mutate(across(c(violent_crime, homicide, rape_legacy, rape_revised, robbery,
           aggravated_assault, property_crime, burglary, larceny,
           motor_vehicle_theft),
           as.integer)) %>%
    rename(State = state_abbr, rape_rate = rape_legacy_rate, 
           murder_rate = homicide_rate, violent_rate = violent_crime_rate,
           assault_rate = aggravated_assault_rate,
           property_rate = property_crime_rate,
           mvt_rate = motor_vehicle_theft_rate, 
           Population = population) %>%
    filter(State != "DC") %>%
    # drop rape rate after 2015 since it switches to new definition
    mutate(rape_rate = ifelse(year > 2016, NA, rape_rate),
           treated = State == "CA", trt = treated * (year >= 2007))


guns <- left_join(crimes, 
                  guns %>% select(year, State, gunrate, nongunrate),
                  by = c("year", "State"))

if(start_year < 1995) {
  crimes <- crimes %>% filter(State != "MS")
}


guns %>%
    mutate(treated = State == "CA", trt = treated * (year >= 2007)) %>%
    mutate_at(vars(contains("rate")), list(log = log)) -> guns

# merge in covariates
cov_data <- read_excel("../data/covariates_2005.xls") %>%
  mutate(logincome = log10(income)) %>%
  rename_with( ~ str_c(., "_2005"), -c(state,year)) %>%
  select(-year)


guns %>%
  inner_join(cov_data, by = c("State" = "state")) -> guns


gunrate_states <- guns %>% 
    filter(year >= start_year, year <= end_year,
           State != "DC", is.na(gunrate)) %>%
    distinct(State) %>% pull(State)
guns %>%
  inner_join(cov_data, by = c("State" = "state")) -> guns


gunrate_states <- guns %>% 
    filter(year >= start_year, year <= end_year,
           State != "DC", is.na(gunrate)) %>%
    distinct(State) %>% pull(State)

```

## Homicides per 100,000, CA vs USA (Figure 1a)
```{r raw_murder}
guns %>%
    filter(year >= start_year, year <= end_year) %>%
    mutate(ca = ifelse(State == "CA", "California", "Rest of the United States")) %>%
    group_by(year, ca) %>%
    summarise(murder_rate = sum(Population * murder_rate) / sum(Population)) %>%
    ggplot(aes(x = year, y = murder_rate, color = ca)) +
    geom_line(size=1) +
    geom_vline(xintercept = 2006, lty = 2) +
    scale_color_brewer("", type = "qual", palette = "Set1", direction = -1) +
    theme_bw(18) + 
    xlab("Year") + 
    ylab("Homicides per 100,000") +
    theme(legend.position = "bottom")
```


## Synthetic control estimate, CA vs Synthetic CA (Figure 1b)
```{r synth_estimates_murder_raw}

# scm + fixed effects
guns %>% 
    filter(year >= start_year, year <= end_year,
           State != "DC") %>%
    augsynth_multiout(murder_rate ~ treated,
                      State, year, t_int = t_int,
                      data = ., 
                      "None", scm = T, fixedeff = T,
                      combine_method = "concat") -> murder_descm

murder_weights <- data.frame(weight = murder_descm$weights)

ctrl_states <- guns %>% filter(! State %in% c("CA", "DC")) %>% distinct(State) %>% pull(State)

murder_weights %>% mutate(state = ctrl_states) %>%
  filter(weight >= 0.01) %>%
  arrange(desc(weight))

summary(murder_descm, inf_type = "jackknife+", alpha = 0.1)$att %>%
    filter(Outcome != "Average") %>%
    rename(att=Estimate, year=Time) %>%
    inner_join(guns %>% 
                filter(State == "CA") %>%
                select(murder_rate, year)
                ) %>%
    mutate(syn_ca = murder_rate - att,
           lower_bound2 = murder_rate - upper_bound,
           upper_bound = murder_rate - lower_bound,
           lower_bound = lower_bound2) %>%
    mutate(murder_rate = murder_rate - mean(murder_rate[year <= 2006]),
           syn_ca = syn_ca - mean(syn_ca[year <= 2006])) %>%
    select(-lower_bound2) %>%
	gather(synthetic, murder_rate, -year, -Outcome, -att, -lower_bound, -upper_bound) %>%
	mutate(synthetic = ifelse(synthetic == "syn_ca", "Synthetic CA", "Observed CA")) %>%
    ggplot(aes(x=year, y=murder_rate, lty = synthetic, color = synthetic)) + 
    geom_line(size=1) + 
    geom_vline(xintercept = 2006.5, lty=2, size = 1) + 
    xlab("Year") +
    ylab("Homicides per 100,000 (de-meaned)") + 
    # coord_cartesian(ylim=c(-0.11, 0.06)) +
    theme_bw(15) +
    scale_color_manual("", values = c(rgb(55,126,184, maxColorValue = 255), "black")) +
	scale_linetype("") +
    guides(color=F, fill=F) + 
    theme(panel.grid.minor.x=element_blank(),
          legend.position="bottom")

```



```{r, utility_functions}

get_posterior_gauss <- function(fit_mtgp) {
  draws <- as_draws_matrix(fit_mtgp$draws())
  means <- subset(draws, variable = "f")
  ppds <- subset(draws, variable = "f_samples")
  sigs <- subset(draws, variable = "sigman")

  return(list(mean_fn=means, ppd=ppds, sd=sigs))
}

get_posterior_pois <- function(fit_mtgp) {
  draws <- as_draws_matrix(fit_mtgp$draws())
  means <- subset(draws, variable = "f")
  ppds <- subset(draws, variable = "f_samples")
  return(list(mean_fn=means, ppd=ppds))
}



organize_post_samples <- function(post, ppd, unit, time, data) {
  
  time <- enquo(time)
  unit <- enquo(unit)
  times <- data %>% distinct(!!time) %>% pull(!!time)
  units <- data %>% distinct(!!unit) %>% pull(!!unit)
  
  # get time-unit-sample pairs
  time <- as_label(time)
  unit <- as_label(unit)
  
  times_units_samples <- expand.grid(1:nrow(post), times, units)

  names(times_units_samples) <- c("sample", time, unit)
  times_units_samples$mean_fn <- c(post)
  times_units_samples$ppd <- c(ppd)

  return(left_join(times_units_samples,
                   data[, c("year", "State", "homicide", "Population")],
                   by=c("year", "State")))
  
}

```



### RMSE for California, Gaussian (Figure 2a)

```{r, gaussian_rmse}
## Homoskedastic Gaussian
res_gaus <- readRDS("../results/mtgp_fits_homoskedastic.RDS")
names(res_gaus) <- 1:length(res_gaus) - 1

compute_summary_gaus <- function(rank, summary_function, filters = function(...){ filter(..., year < t_int, State == "CA") }) {
  fit <- res_gaus[[rank]]
  post <- get_posterior_gauss(fit)$mean_fn
  y_pred <- get_posterior_gauss(fit)$ppd
  post_data <- organize_post_samples(post,
                        y_pred,
                        unit = State,
                        time = year,
                        data = crimes %>% filter(year >= start_year))
  results_table <- post_data %>%
    mutate(scaled_population = Population/1e5) %>%
    filters %>% 
    group_by(sample) %>%
    summary_function %>%
    mutate(rank = rank) %>% ungroup()

    results_table
}

mse_fn <- function(...){ summarize(..., 
                                         mse_true = sqrt(mean((mean_fn - homicide/scaled_population)^2)), 
                                         mse_ppd = sqrt(mean((mean_fn - ppd)^2))) }

mse_table_ca <- map_dfr(names(res_gaus), function(x) compute_summary_gaus(x, mse_fn, filters = function(...) filter(..., State == "CA", year < t_int))) %>%
                          mutate(rank = as.factor(rank))

pvals <- mse_table_ca %>% 
  group_by(rank) %>%
  summarize(pval = round(2*min(mean(mse_true > mse_ppd), mean(mse_true <= mse_ppd)), digits=2))

ca_mse_plot <- mse_table_ca %>% 
  rename(Observed=mse_true, PPD=mse_ppd) %>%
  pivot_longer(cols=c("PPD", "Observed"), names_to="Type", values_to="mse") %>% 
  ggplot() + 
  ggtitle("Gaussian") +
  geom_density_ridges(aes(x=mse, y=as.factor(rank), fill=Type), alpha=0.4) + 
  xlab("RMSE") + ylab("Rank") + theme_minimal(base_size=16) + 
  geom_text(data=pvals, aes(label=pval, y=1:length(res_gaus)+0.55, x=0.45), size=6.5, nudge_x=0.015) + 
  xlim(c(0, .5))

ca_mse_plot

```



### RMSE for California, Poisson model (Figure 2b)

```{r, poisson_rmse}
## POISSON
res_pois <- readRDS("../results/mtgp_fits_poisson.RDS")

compute_summary_pois <- function(rank, 
                            summary_function, 
                            filters = function(...){ filter(..., year < t_int, 
                                                            State == "CA") }
                            ) {
  fit <- res_pois[[rank]]
  post <- get_posterior_pois(fit)$mean_fn
  y_pred <- get_posterior_pois(fit)$ppd

  post_data <- organize_post_samples(post,
                        y_pred,
                        unit = State,
                        time = year,
                        data = crimes %>% filter(year >= start_year))
  results_table <- post_data %>%
    mutate(scaled_population = Population/1e5) %>%
    filters %>% group_by(sample) %>%
    summary_function %>%
    mutate(rank = rank) %>% ungroup()

    results_table
}

mse_fn <- function(...){ 
  summarize(...,  mse_true = 
              sqrt(mean((mean_fn/scaled_population - homicide/scaled_population)^2)), 
                  mse_ppd = sqrt(mean((mean_fn/scaled_population - ppd/scaled_population)^2))) }

mse_table_all <- map_dfr(names(res_pois), function(x) compute_summary_pois(x, mse_fn, filters = function(...) filter(..., year < t_int))) %>% mutate(rank = as.factor(rank))

all_mse_plot <- mse_table_all %>% pivot_longer(cols=c("mse_true", "mse_ppd"), names_to="type", values_to="mse") %>% 
  ggplot(aes(x=mse, y=as.factor(rank), fill=type)) + 
  geom_density_ridges(alpha=0.4) + 
  xlab("RMSE") + ylab("Rank")

mse_table_ca <- map_dfr(names(res_pois), function(x) compute_summary_pois(x, mse_fn, filters = function(...) filter(..., State == "CA", year < t_int))) %>% mutate(rank = as.factor(rank))


pvals <- mse_table_ca %>% 
  group_by(rank) %>%
  summarize(pval = round(2*min(mean(mse_true > mse_ppd), mean(mse_true <= mse_ppd)), digits=2))

ca_mse_plot <- mse_table_ca %>% 
  rename(Observed=mse_true, PPD=mse_ppd) %>%
  pivot_longer(cols=c("PPD", "Observed"), names_to="Type", values_to="mse") %>% 
  ggplot() + 
  ggtitle("Poisson") +
  geom_density_ridges(aes(x=mse, y=as.factor(rank), fill=Type), alpha=0.4) + 
  xlab("RMSE") + ylab("Rank") + theme_minimal(base_size=16) + 
  geom_text(data=pvals, aes(label=pval, y=1:length(res_pois)+0.55, x=0.4), size=6.5, nudge_x=0.015) + 
  xlim(c(0, 0.5))

all_mse_plot <- mse_table_all %>% 
  rename(Observed=mse_true, PPD=mse_ppd) %>%
  pivot_longer(cols=c("PPD", "Observed"), names_to="Type", values_to="mse") %>% 
  ggplot() + 
  geom_density_ridges(aes(x=mse, y=as.factor(rank), fill=Type), alpha=0.4) + 
  xlab("RMSE") + ylab("Rank") + theme_minimal(base_size=16) + 
  geom_text(data=pvals, aes(label=pval, y=1:length(res_pois)+0.55, x=0.4), size=6.5, nudge_x=0.015)

ca_mse_plot
```



## Pre-treatment imbalance for Poisson model with Rank 5 (Figure 3)

```{r ca_pois_balance_gap_rank5}

balance_check_pois <- function(index, 
                               filters = function(...){ filter(..., year < t_int, State == "CA") }
) {
  fit <- res_pois[[index]]
  post <- get_posterior_pois(fit)$mean_fn
  y_pred <- get_posterior_pois(fit)$ppd
  
  post_data <- organize_post_samples(post,
                                     y_pred,
                                     unit = State,
                                     time = year,
                                     data = crimes %>% filter(year >= start_year))
  
  post_data %>%
    mutate(scaled_population = Population/1e5) %>%
    filters %>% 
    group_by(sample, year) %>%
    summarize(
      balance_obs = (homicide - mean_fn)/scaled_population,
      balance_ppd = (ppd - mean_fn)/scaled_population
    ) %>%
    mutate(rank = index-1) %>% 
    ungroup() -> results_table
  
  return(results_table)
}

full_pois_draws <- map_dfr( 1:8, function(i){ balance_check_pois(index = i) })

full_pois_draws %>%
  filter(rank == 5) %>%
  group_by(year) %>%
  summarize(mean_imbalance = mean(balance_obs) ) %>% 
  mutate(type = "obs") -> pois_summary

full_pois_draws %>%
  filter(rank == 5) %>%
  pivot_longer(c(balance_obs, balance_ppd),
               values_to = "balance",
               names_prefix = "balance_",
               names_to = "type") %>%
  # rename("Rank" = rank) %>%
  group_by(year) %>%
  ggplot(aes(x = year, y = balance, fill = type, color = type)) + #width = ..density.., 
  geom_hline(yintercept = 0, lty = 1) +
  geom_vridgeline(aes(x = factor(year), width = ..density..), stat="ydensity", trim=TRUE, alpha = 0.4, scale = 0.15) +
  xlab("") + ylab("") + 
  # ylab("Difference in homicides per 100,000") + 
  ggtitle("Gap imbalance: Difference in homicides per 100,000") +
  theme_bw() + 
  # scale_x_discrete(labels = c("", "1998", "", "", "", "2002", "", "", "", "2006")) + 
  ylim(-0.9,0.9) -> p

p + geom_point(data = pois_summary, aes(x = factor(year), y = mean_imbalance), size = 1.5) -> p_gap

```

```{r ca_pois_balance_raw_rank5}
ranks <- 0:7

posts_pois <- lapply(res_pois, get_posterior_pois)

post_pred_ranks_pois <- lapply(ranks, function(r) organize_post_samples(posts_pois[[r+1]]$mean_fn, 
                                                                        posts_pois[[r+1]]$ppd,
                                                                        unit = State, time = year, 
                                                                        data = crimes %>% filter(year >= start_year)))

names(post_pred_ranks_pois) <- ranks

bind_rows(
  post_pred_ranks_pois, .id = "Rank"
  ) %>%
  group_by(year, State, Rank) %>%
  filter(year < 2007) %>%
  filter(State == "CA") %>%
  filter(Rank == 5) %>% 
  summarise(
        post_pred_mean = mean(ppd),
        post_pred_upper = quantile(ppd, .975),
        post_pred_lower = quantile(ppd, .025),
        post_pred_upper50 = quantile(ppd, 0.75),
        post_pred_lower50 = quantile(ppd, 0.25)
      ) %>%
  inner_join(crimes, by = c("State", "year")) %>%
  ggplot(aes(x = year, group = State)) +
  geom_ribbon(aes(ymax = post_pred_upper/ (Population / 1e5), ymin = post_pred_lower/ (Population / 1e5)),
              fill = "grey50", alpha = .5) +
  geom_ribbon(aes(ymax = post_pred_upper50/ (Population / 1e5), ymin = post_pred_lower50/ (Population / 1e5)),
              fill = "grey20", alpha = .5) +
  geom_line(aes(y = post_pred_mean / (Population / 1e5)), lwd = 1.25) + #color = rgb(228,26,28, maxColorValue = 255)) +
  geom_line(aes(y = murder_rate), lwd = 1, color = rgb(228,26,28, maxColorValue = 255)) +
  # geom_vline(xintercept = 2007, lty = 2) +
  # facet_wrap(~ Rank, labeller = label_both, ncol=4) +
  xlab("") + ylab("") + 
  # ylab("Homicides per 100,000") +
  # ggtitle("Observed and posterior predictive distribution of homicide counts") +
     theme(axis.text.x =element_blank()) +
  ggtitle("Raw imbalance: Homicides per 100,000") + 
  theme_bw() -> p_raw
```



```{r ca_pois_balance_rank5}
p_raw / p_gap +
    plot_annotation(title = 'Pre-treatment imbalance: Poisson MTGP with Rank 5')

```



## Plot estimates (Figure 4)


```{r ca_pois_estimates_raw_rank5}
  post_pred_ranks_pois$`5` %>% 
  group_by(year, State) %>%
  filter(State == "CA", year <= 2016) %>%
  # filter(Rank == 5) %>% 
  summarise(
        post_pred_mean = mean(ppd),
        post_pred_upper = quantile(ppd, .975),
        post_pred_lower = quantile(ppd, .025),
        post_pred_upper50 = quantile(ppd, 0.75),
        post_pred_lower50 = quantile(ppd, 0.25)
      ) %>% 
  inner_join(crimes, by = c("State", "year"))  %>%
  mutate(post_pred_mean = post_pred_mean / (Population / 1e5),
         post_pred_upper = post_pred_upper / (Population / 1e5),
         post_pred_lower = post_pred_lower / (Population / 1e5),
         post_pred_upper50 = post_pred_upper50 / (Population / 1e5),
         post_pred_lower50 = post_pred_lower50 / (Population / 1e5)) -> pois_rank5_posterior
```


```{r}
  pois_rank5_posterior %>%
  ggplot(aes(x = year, group = State)) +
  geom_ribbon(aes(ymax = post_pred_upper, ymin = post_pred_lower),
              fill = "grey50", alpha = .5) +
  geom_ribbon(aes(ymax = post_pred_upper50, ymin = post_pred_lower50),
              fill = "grey20", alpha = .5) +
  geom_line(aes(y = post_pred_mean), lwd = 1.25) + #color = rgb(228,26,28, maxColorValue = 255)) +
  geom_line(aes(y = murder_rate), data = . %>% filter(year < 2007), lwd = 1, color = rgb(228,26,28, maxColorValue = 255)) +
  geom_line(aes(y = murder_rate), data = . %>% filter(year >= 2007), lwd = 1, color = rgb(228,26,28, maxColorValue = 255)) +
  geom_vline(xintercept = 2006.5, lty = 2) +
  # facet_wrap(~ Rank, labeller = label_both, ncol=4) +
  xlab("") + ylab("") + 
  ylab("Homicides per 100,000") +
  # ggtitle("Observed and posterior predictive distribution of homicide counts") +
     theme(axis.text.x =element_blank()) +
  # ggtitle("Raw imbalance: Homicides per 100,000") + 
  # ylim(0,11) +
  theme_bw() -> p_raw

```


```{r}
  pois_rank5_posterior %>% 
  mutate(post_pred_mean = murder_rate - post_pred_mean,
         post_pred_upper = murder_rate - post_pred_upper,
         post_pred_lower = murder_rate - post_pred_lower,
         post_pred_upper50 = murder_rate - post_pred_upper50,
         post_pred_lower50 = murder_rate - post_pred_lower50) %>%
  ggplot(aes(x = year, group = State)) +
  geom_hline(yintercept = 0) +
  geom_ribbon(aes(ymax = post_pred_upper , ymin = post_pred_lower),
              fill = "grey50", alpha = .5) +
  geom_ribbon(aes(ymax = post_pred_upper50 , ymin = post_pred_lower50 ),
              fill = "grey20", alpha = .5) +
  geom_line(aes(y = post_pred_mean), lwd = 1.25) + #color = rgb(228,26,28, maxColorValue = 255)) +
  geom_vline(xintercept = 2006.5, lty = 2) +
  # facet_wrap(~ Rank, labeller = label_both, ncol=4) +
  xlab("") + ylab("") + 
  ylab("Difference in Homicides per 100,000") +
  # ggtitle("Observed and posterior predictive distribution of homicide counts") +
     theme(axis.text.x =element_blank()) +
  # ylim(-8, 1) +
  theme_bw() -> p_gap

```




```{r ca_pois_est_rank5}
p_raw / p_gap
```



## Benefit-Cost (Figure 5)

```{r}
  cost17 <- 11300000
  pop17 <- crimes %>% filter(State == "CA", year == 2017) %>% select(Population) %>% pull()

  post_pred_ranks_pois$`5` %>% 
  filter(State == "CA") %>%
  group_by(year) %>%
  inner_join(crimes, by = c("State", "year", "Population"))  %>%
  mutate(gap = murder_rate - ppd / (Population / 1e5)) %>%
  filter(year >= 2007 & year <= end_year) %>%
  group_by(sample) %>% 
  summarize(impact = mean(gap),
            impact_count = mean(gap_count),
            impact17 = (-1) * cost17 /  (mean(gap) * (pop17 / 1e5))) -> impact_posterior
```

```{r}
impact_posterior %>%
  ggplot(aes(x = impact)) + geom_density(color = "black", fill = "grey", alpha = 0.7) +
  theme_bw() + 
  xlab("Impact on murder rate (per 100,000)") + 
  ylab("") +  
  ggtitle("Impact on murder rate") + 
  geom_vline(data = impact_posterior %>% summarize(qs = quantile(impact, c(0.025, 0.50, 0.975))),
             aes(xintercept = qs),
              color = "black", lty = c(3,1,3)) +
  # scale_x_continuous(labels = scales::dollar, limits = c(0, 100000)) +
  theme(axis.text.y = element_blank()) -> p_impact_raw

```


```{r}
impact_posterior %>%
  filter(impact17 < 100000,
         impact17 > -50000) %>%
  ggplot(aes(x = impact17)) + geom_density(color = "black", fill = "grey", alpha = 0.7) +
  theme_bw() + 
  xlab("Estimated cost per murder avoided") + 
  ylab("") +  
  geom_vline(data = impact_posterior %>% filter(impact17 < 100000,
         impact17 > -50000) %>%
         summarize(qs = quantile(impact17, c(0.025, 0.50, 0.975))),
             aes(xintercept = qs),
              color = "black", lty = c(3,1,3)) +
  ggtitle("Cost per murder avoided") +
  scale_x_continuous(labels = scales::dollar, limits = c(0, 100000)) +
  theme(axis.text.y = element_blank()) -> p_impact_cost

```


```{r ca_overall_impact_pois_rank5}
p_impact_raw + p_impact_cost +
  plot_annotation(title = 'Posterior Estimates of Impact of APPS on Murders in CA')
```



## In-time placebos (Figure 6)








```{r fit_pois_placebo, eval = F}

placebo_pois <- function(t_int){
  read_dta("../ucrthrough2018.dta") %>%
    mutate(across(c(violent_crime, homicide, rape_legacy, rape_revised, robbery,
                    aggravated_assault, property_crime, burglary, larceny,
                    motor_vehicle_theft),
                  as.integer)) %>%
    rename(State = state_abbr, rape_rate = rape_legacy_rate, 
           murder_rate = homicide_rate, violent_rate = violent_crime_rate,
           assault_rate = aggravated_assault_rate,
           property_rate = property_crime_rate,
           mvt_rate = motor_vehicle_theft_rate, 
           Population = population) %>%
    filter(State != "DC") %>%
    # drop rape rate after 2015 since it switches to new definition
    mutate(rape_rate = ifelse(year > 2016, NA, rape_rate),
           treated = State == "CA", trt = treated * (year >= t_int)) -> crimes
  fit_mtgp_pois(
    outcome=homicide, 
    trt=treated, 
    unit=State, 
    time=year, 
    t_int=t_int, 
    data=crimes %>% filter(year >= start_year), 
    n_k_f=5,
    #num_nonzero=4,
    iter_warmup = 500, iter_sampling = 500,
    chains = 4, parallel_chains = 4,
    adapt_delta = 0.9, max_treedepth = 13)
}
pois_placebo <- lapply(2006 - 1:4, placebo_pois)
saveRDS(pois_placebo, "../results/pois_placebo.RDS")
```


```{r pois_placebo}

pois_placebo <- readRDS("../results/pois_placebo.RDS")

lapply(pois_placebo, get_posterior_pois) -> pois_placebo

pois_placebo_post <- lapply(1:length(pois_placebo),
    function(k) organize_post_samples(pois_placebo[[k]]$mean_fn,
                                     pois_placebo[[k]]$ppd,
                                     unit = State,
                                     time = year,
                                     data = crimes %>% filter(year >= start_year)))

map_df(1:length(pois_placebo),
  function(k) {
    pois_placebo_post[[k]] %>%
      filter(State == "CA", year <= end_year) %>%
      mutate(gap = (homicide - ppd) / Population * 1e5 ) %>%
      group_by(year) %>%
      summarise(homicide = mean(homicide),
                post_pred_mean = mean(gap),
                post_pred_lower50 = quantile(gap, 0.25),
                post_pred_lower = quantile(gap, 0.025),
                post_pred_upper50 = quantile(gap, 0.75),
                post_pred_upper = quantile(gap, 0.975)) %>%
      ungroup() %>%
      mutate(t_int = 2006 - k)
  }) %>%
  filter(year <= 2006) %>%
  ggplot(aes(x = year)) +
  geom_hline(yintercept = 0) +
  geom_ribbon(aes(ymax = post_pred_upper , ymin = post_pred_lower),
            fill = "grey50", alpha = .5) +
  geom_ribbon(aes(ymax = post_pred_upper50 , ymin = post_pred_lower50 ),
            fill = "grey20", alpha = .5) +
  geom_line(aes(y = post_pred_mean), lwd = 1.25) +
  geom_vline(aes(xintercept = t_int + 0.5), color = "red", lty = 2) +
  # geom_vline(xintercept = 2006.5, lty = 2) +
  facet_wrap(~t_int, nrow = 2, labeller = as_labeller(function(x) paste("Placebo APPS Year:", x))) +
  xlab("") +
  ylab("Difference in Homicides per 100,000") +
  # ggtitle("Observed and posterior predictive distribution of homicide counts") +
  theme(axis.text.x =element_blank()) +
  theme_bw()


```

## Gun related vs non-gun related (Figure 7)




```{r, preprocess_multioutput}
start_year <- 1997
end_year <- 2016
t_int <- 2007
gunrate_states <- read_dta("ucrpanel2.dta") %>% 
  filter(year >= start_year, year <= end_year, State != "DC") %>% 
  group_by(State) %>% 
  summarise(hasguns=sum(nongunrate)) %>% 
  drop_na() %>% 
  pull(State)
# put the data into long format
read_dta("ucrpanel2.dta") %>% 
  filter(State != "DC") %>% 
  filter(year >= start_year) %>% 
  filter(year <= end_year) %>% 
  select(year, State, Population, gunrate, nongunrate) %>%
  pivot_longer(cols=c('gunrate', 'nongunrate'), names_to="crime_type") %>%
  filter(State %in% gunrate_states) %>% 
  drop_na() %>%
  mutate(
    treated=(State == "CA") * (year >= 2007),
    inv_pop=1/(Population/1e5),
    value_per=(value)
  ) -> long_df
num_years = end_year - start_year + 1
num_units = length(unique(long_df$State))
num_outcomes = 2
year_vector = start_year:end_year
# shape into a three dimensional array that is [outcome, year, unit]
murder_assault_arr = aperm(
  array(as.matrix(long_df  %>% select(value_per)), dim = c(num_years, num_units, 2)), 
  c(3, 1, 2)
)
control_idx = which(
  as.matrix(long_df %>% filter(crime_type=='gunrate') %>% select(treated)) == 0
)
inv_population = matrix(as.matrix((
  long_df %>% filter(crime_type == 'gunrate') %>% select(inv_pop) 
)), num_years, num_units)
```

```{r}

organize_post_samples_mo <- function(samples, unit, time, data, noutcomes=1) {
  time <- enquo(time)
  unit <- enquo(unit)
  times <- data %>% distinct(!!time) %>% pull(!!time)
  units <- data %>% distinct(!!unit) %>% pull(!!unit)
  
  # get time-unit-sample pairs
  time <- as_label(time)
  unit <- as_label(unit)
  times_units_samples <- expand.grid(1:max(samples$.draw), units, times, 1:noutcomes)
  names(times_units_samples) <- c("sample", unit, time, "crime_type")
  times_units_samples <- times_units_samples %>% mutate(crime_type = ifelse(crime_type==1, "gunrate", "nongunrate"))
  times_units_samples %>% mutate(year=as.integer(year))
  data <- data %>% mutate(year == as.integer(year))
  times_units_samples <- cbind(times_units_samples, samples)

  return(left_join(times_units_samples,
                   data[, c("year", "State", "crime_type", "value", "inv_pop")],
                   by=c("year", "State", "crime_type")))
  
}

```



```{r}
res <- readRDS("../results/mtgp_fit_multi.RDS")

all_samples <- map_dfr(names(res), function(rank_name) {
  print(rank_name)
  fit <- res[[rank_name]]
  draws <- as_draws_matrix(fit)
  samps <- draws %>% spread_draws(f[M, N, D], f_samples[M, N, D], sigman[M])
  all_samples <- organize_post_samples_mo(samps, unit = State,
                        time = year,
                        data = long_df %>% filter(year >= start_year),
                        noutcomes = max(samps$M))

  all_samples$rank <- rank_name
  all_samples
})
```


```{r rank_five}
  all_samples %>% 
  filter(rank=="5") %>%
  group_by(year, State, crime_type)  %>%
  summarise(
        post_pred_mean = mean(f),
        post_pred_upper = quantile(f, .975),
        post_pred_lower = quantile(f, .025),
        post_pred_upper50 = quantile(f, 0.75),
        post_pred_lower50 = quantile(f, 0.25),
        true = mean(value)
      ) %>%
  filter(State == "CA") %>%
  ggplot(aes(x = year, group = crime_type)) +
  geom_ribbon(aes(ymax = post_pred_upper50, ymin = post_pred_lower50),
              fill = "grey20", alpha = .5) +
  geom_ribbon(aes(ymax = post_pred_upper, ymin = post_pred_lower),
              fill = "grey50", alpha = .5) +
  geom_line(aes(y = post_pred_mean), size=1) +
  geom_line(aes(y = true), color = rgb(228,26,28, maxColorValue = 255), size=1) +
  geom_vline(xintercept = 2007, lty = 2) +
  facet_wrap(~ crime_type, labeller=labeller(crime_type = c("gunrate" = "Gun Related", "nongunrate" = "Non-gun related")), scales="free") +
  xlab("") +
  ylab("Homicides per 100,000") +
  ggtitle("Observed and posterior predictive distribution of homicide rates") +
  theme_bw() 
```


